#ifndef CHECKERS_CONSTANTS_H
#define CHECKERS_CONSTANTS_H

enum {
  CHECKERS_MAX_BOARD_SIZE = 10,
  CHECKERS_MAX_SQUARES = 50,
  CHECKERS_MAX_MOVE_LENGTH = 50,
  CHECKERS_MAX_BOARD_BYTES = 25
};

#endif
